name: Run Black

on:
  push:
    branches: [main]
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Black on changed files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
            | grep '\.py$' \
            | xargs black --check
